zod-nestjs: Allow using the zodSchema field to construct other types
The static zodSchema field on the DTO classes now maintains the schema
type that is passed in, which allows it to be used to construct other
schemas. Previously this zodSchema field had type "CompatibleZodType"
rather than "T extends CompatibleZodType" which meant that most of the
type information was lost.

Workarounds:
Although not as concise, the schema value can be exported separately or
the zodSchema field can be redefined on each DTO class that needs it.

Breaking change:
The "T" in ZodDtoStatic<T> has changed from the output type to the
schema type. Code that is using the ZodDtoStatic type directly may need
to be updated. No changes are needed if just using the DTOs.

Examples:

// user.dto.ts

import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod';

const schema = z.object({ name: z.string() });

export class UserDto extends createZodDto(schema) {}

// users-list.dto.ts (has an array of users)

import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod';
import { UserDto } from './user.dto';

// Previously produced a TypeScript error: Property 'array' does not exist on type 'CompatibleZodType'.
const schema = z.object({ items: UserDto.zodSchema.array() });

export class UsersListDto extends createZodDto(schema) {}

// extended-user.dto.ts (a user with an additional field)

import { createZodDto } from '@anatine/zod-nestjs';
import { z } from 'zod';
import { UserDto } from './user.dto';

// Previously produced a TypeScript error: Property 'extend' does not exist on type 'CompatibleZodType'.
const schema = UserDto.zodSchema.extend({ group: z.string() });

export class ExtendedUserDto extends createZodDto(schema) {}